"""empty message

Revision ID: 9801683315aa
Revises: 2faa6811639c
Create Date: 2019-10-21 18:51:21.650950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9801683315aa'
down_revision = '2faa6811639c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_fund_depost', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'admin_fund_depost', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_fund_depost', type_='foreignkey')
    op.drop_column('admin_fund_depost', 'user_id')
    # ### end Alembic commands ###
